version: "2.3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - ./fixtures:/var/fixtures
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-prootpassword"]
      timeout: 20s
      retries: 10
    networks:
      - next-p

networks:
  next-p:
    driver: bridge
